// Code generated by goctl. DO NOT EDIT.
package types

type RegisterUserReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginUserReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginUserResp struct {
	Expire int64  `json:"expire"`
	Token  string `json:"token"`
}

type UserInfoReq struct {
	Uid int64 `json:"uid"`
}

type UserResp struct {
	Id        int64  `json:"id"`
	UserName  string `json:"userName"`
	Password  string `json:"password"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}
